<?php

class db extends mysqli{
    function query(string $query, int $result_mode = MYSQLI_STORE_RESULT): mysqli_result|bool
    {
        try {
           return parent::query($query, $result_mode); // TODO: Change the autogenerated stub
        } catch (mysqli_sql_exception $e) {
            die ($e->getMessage() . '<br/>' . $e->getFile() . ' linea ' . $e->getLine() . '<pre>' . $query . '</pre>');
        }
    }
}